
const actionTypes = {
    DOWNLOAD_DATA: "DOWNLOAD_DATA",
    TOGGLE_LOADING: "TOGGLE_LOADING",
    SET_ERROR: "SET_ERROR",
    SELECT_NOTE: "SELECT_NOTE",
    TOGGLE_THEME: "TOGGLE_THEME",
    UPDATE_NOTE_TITLE: "UPDATE_NOTE_TITLE",
    UPDATE_NOTE_DESCRIPTION: "UPDATE_NOTE_DESCRIPTION",
    SYNC_DATA: "SYNC_DATA",
    DELETE_NOTE: "DELETE_NOTE",
    CREATE_NOTE: "CREATE_NOTE",
};
export default  actionTypes;