
 const actionTypes = {
   UPDATE_NOTE: "UPDATE_NOTE",
   CREATE_NOTE: "CREATE_NOTE",
   LOAD_DATA: "LOAD_DATA",
   TOGGLE_LOADING: "TOGGLE_LOADING",
   SET_ERROR: "SET_ERROR",
   SELECT_NOTE: "SELECT_NOTE",
   TOGGLE_THEME: "TOGGLE_THEME",
   DELETE_NOTE: "DELETE_NOTE"
};
 export default  actionTypes;